#!/usr/bin/env bash
#MAKE INSTALL NGINGX (WEB-2) AND CHECK STATE

#sudo apt-get -y update
#sudo apt-get -y install nginx


#SEND GUSTOM HEADER REQUEST

header_con="add_header X-Served-By \$hostname;"

sudo sed -i "/http {/a $header_con" /etc/nginx/nginx.conf

sudo systemctl restart nginx
