#!/usr/bin/env bash
#MAKE INSTALL NGINGX (WEB-2) AND CHECK STATE

sudo apt-get -y update
sudo apt-get -y install nginx


#SEND GUSTOM HEADER REQUEST
sed -i "/listen 80 default_server/a \\\tadd_header X-Served-By $(hostname);" /etc/nginx/sites-available/default


sudo systemctl restart nginx
