#!/usr/bin/env bash
#fix problem port 80 
sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo service nginx start
sudo service nginx restart
