#!/usr/bin/env bash

#Check if nginx install
sudo apt-get update
sudo apt-get -y install nginx

#Check nginx if running
sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo service nginx start

#Restart nginx
sudo service nginx restart
