#!/bin/bash

#Check if nginx install
sudo apt-get update
sudo apt-get install nginx -y


# Check nginx if running
sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo systemctl start nginx
sudo systemctl enable nginx


# Restart nginx
sudo service nginx restart
